import '../styles/globals.css';
import Head from 'next/head';
import styles from '../styles/_app.module.css';

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devempire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Component {...pageProps} />
      </main>
    </div>
  );
};

export default MyApp
